version: '3'

services:
  keycloak:
    ports:
      - "8082:8080"
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    networks:
      - apps
      
  auth-app:
    build:
      context: ./../auth-app
      dockerfile: ./../auth-app/auth-app.dockerfile
    restart: always
    ports:
      - "8083:8080"
    container_name: auth-app
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - apps

  url-shortener-app:
    build:
      context: ./../url-shortener-app
      dockerfile: ./../url-shortener-app/url-shortener-app.dockerfile
    restart: always
    ports:
      - "8084:8080"
    container_name: url-shortener-app
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - apps

networks:
  apps:
    driver: bridge
